# Generated by Django 5.0.7 on 2024-07-16 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('stock_status', models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock')], max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('imprimante', 'Imprimante'), ('ancre', 'Ancre'), ('ruban', 'Ruban'), ('bac', 'Bac de dechet')], max_length=50)),
                ('tags', models.CharField(help_text='Create up to three tags about your product', max_length=255)),
                ('rating', models.FloatField(default=3)),
                ('video_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(blank=True, max_length=255, null=True)),
                ('print_speed', models.CharField(max_length=255)),
                ('first_print_out_time', models.CharField(max_length=255)),
                ('max_monthly_duty_cycle', models.CharField(max_length=255)),
                ('recommended_monthly_volume', models.CharField(max_length=255)),
                ('printer_language_duplex_mode', models.CharField(max_length=255)),
                ('printer', models.CharField(max_length=255)),
                ('glass', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='home.product')),
            ],
        ),
    ]
