# Generated by Django 5.0.7 on 2024-07-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Bestseller',
            field=models.IntegerField(default=0),
        ),
    ]
