# Generated by Django 5.0.7 on 2024-07-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_formsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecification',
            name='fonctions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='gtin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='marque',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
